name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📁 Prepare deployment directory
      run: |
        mkdir dist
        cp garav2.html dist/

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /www/contagiristatico/
        local-dir: ./dist/
